/**
 * CertificatePrint — Print-only component for the Certificate of No Objection.
 * Supports two modes:
 *   1. Existing tree: receives `tree` + `clientName` props
 *   2. Walk-in request: receives `walkInData` prop with all fields
 */
import santaCruzLogo from '../assets/Santa Cruz Logo.png';
import menroLogo from '../assets/MENRO Santa Cruz logo.png';

export default function CertificatePrint({ tree, clientName, contactInfo, reason, walkInData }) {
  // Determine data source
  let species, scientificName, merchantableHeight, location, lat, lng, client, numTrees;

  if (walkInData) {
    species = walkInData.species || 'Unknown Species';
    scientificName = walkInData.scientificName || 'N/A';
    merchantableHeight = 'N/A';
    location = walkInData.address || 'Santa Cruz, Laguna';
    lat = walkInData.latitude?.toFixed(6) || 'N/A';
    lng = walkInData.longitude?.toFixed(6) || 'N/A';
    client = walkInData.clientName || 'N/A';
    numTrees = walkInData.numberOfTrees || 1;
  } else if (tree) {
    species = tree.species || 'Unknown Species';
    scientificName = tree.scientific_name || tree.scientificName || 'N/A';
    merchantableHeight = tree.merchantable_height || tree.heightClass || 'N/A';
    location = tree.barangay || tree.address || 'Santa Cruz, Laguna';
    lat = tree.latitude?.toFixed(6) || 'N/A';
    lng = tree.longitude?.toFixed(6) || 'N/A';
    client = clientName || 'N/A';
    numTrees = 1;
  } else {
    return null;
  }

  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const treeCountText = numTrees > 1
    ? `${numTrees} (${numTrees}) standing`
    : 'a single standing';

  return (
    <div data-testid="certificate-print" className="hidden print:block print:fixed print:inset-0 print:z-[99999] print:bg-white">
      <div className="w-full max-w-[210mm] mx-auto px-12 py-8 text-black text-sm leading-relaxed font-serif">
        {/* Header */}
        <div className="flex items-center justify-between mb-2">
          <img
            src={santaCruzLogo}
            alt="Municipality of Santa Cruz seal"
            className="w-20 h-20 object-contain"
          />
          <div className="text-center flex-1 px-4">
            <p className="text-xs">Republic of the Philippines</p>
            <p className="text-xs">Province of Laguna</p>
            <p className="text-xs font-semibold">Municipality of Santa Cruz</p>
            <p className="text-xs font-semibold uppercase tracking-wide mt-1">Office of the Municipal Mayor</p>
          </div>
          <img
            src={menroLogo}
            alt="MENRO Santa Cruz seal"
            className="w-20 h-20 object-contain"
          />
        </div>

        <hr className="border-black my-4" />

        {/* Title */}
        <h1 className="text-center text-lg font-bold uppercase tracking-wide mt-8 mb-8">
          Certificate of No Objection
        </h1>

        {/* Body */}
        <div className="space-y-6 text-justify text-sm leading-7">
          <p className="indent-8">
            This is to certify that {treeCountText} <strong>{species}</strong> Specie
            (<em>{scientificName}</em>) with estimated volume of more or less <strong>{merchantableHeight}</strong> cubic
            meter is owned by <strong>{client}</strong>, situated at {location}, Santa Cruz,
            Laguna (Lat: {lat}, Long: {lng}) within the private land.
          </p>

          <p className="indent-8">
            Certified further that the Local Government of Santa Cruz through Municipal Environmental
            and Resource Office interposes no objection to the said {numTrees > 1 ? `${numTrees} standing` : 'single standing'} <strong>{species}</strong> Specie.
          </p>

          <p className="indent-8">
            ISSUED this <strong>{currentDate}</strong>, as requested by <strong>{client}</strong> in
            support of his/her application for Special Private Land Timber Permit and Cutting Permit to
            DENR Region IV-A.
          </p>
        </div>

        {/* Signature */}
        <div className="mt-16 text-center">
          <div className="inline-block">
            <div className="w-64 border-b border-black mb-1"></div>
            <p className="text-xs font-semibold uppercase">Municipal Mayor</p>
            <p className="text-xs text-gray-600">Municipality of Santa Cruz, Laguna</p>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 text-xs text-gray-500 text-center">
          <p>This certificate is computer-generated by the Tree Inventory & Carbon Dashboard.</p>
          <p>Document ID: {tree?.id?.slice(0, 8) || 'WI-' + Date.now().toString(36)} • Generated: {currentDate}</p>
        </div>
      </div>
    </div>
  );
}
